copyright: Copyright &copy; 2016

site_name: boost.msm-lite
site_url: http://www.mkdocs.org
site_author: Krzysztof Jusiak
repo_url: https://github.com/krzysztof-jusiak/msm-lite
repo_name: msm-lite
use_directory_urls: false
theme_dir: boost

docs_dir: .
pages:
- Introduction: index.md
- Overview: overview.md
- Tutorial: tutorial.md
- User Guide: user_guide.md
- Examples: examples.md
- CHANGELOG: CHANGELOG.md
- TODO: TODO.md
